### ISSUE TITLE
Actions for updating spot prices is failing since 2023-04-15

### ISSUE THREAD

**Issue by freol35241** [u9n/spot#1]
It seems there is no data for 2023-04-15 in the fetched dataset:

https://github.com/u9n/spot/actions/runs/4706481825/jobs/8347742793#step:6:39

**Comment by freol35241** [comment]
And now its working again.

Well, sorry for being a bit trigger happy on creating this issue and thank you for this api!

Note to self (and perhaps others): Do NOT assume that the `/latest` endpoint automatically returns todays and tomorrows prices!

**Comment by Krolken** [comment]
Had some time to look at this now. Seems like the values was not available in the ENTSO-E platform. So it was not possible to add them to the API. Usually this does not happen as there are a few hours to rerun failed jobs on the day ahead prices so they usually gets added the day before.

But we are not in control of the ENTSO-E platform so not much to do about it if the data is missing there. Also we don't monitor this service to closely as it is a free service. 

`/latest` will contain the latest data if available in the ENTSO-E platform. If you are building an algorithm to do load control I would recommend to always have a default usage/price distribution for at least each month to use as fallback if the API is down or missing data.
